# Generated by Django 3.2.2 on 2021-05-12 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='discreption',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
