# Generated by Django 3.2.2 on 2021-05-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_discreption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='discreption',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
    ]
