# Generated by Django 3.2.2 on 2021-05-20 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_discreption'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='catagoery',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
