# Generated by Django 3.2.2 on 2021-05-21 17:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210521_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 21, 17, 42, 11, 651144, tzinfo=utc), null=True),
        ),
    ]
