# Generated by Django 3.2.2 on 2021-05-21 19:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_post_published_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='corona_help',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('discreption', models.TextField()),
                ('contact', models.CharField(blank=True, max_length=1000, null=True)),
                ('published_date', models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 21, 19, 40, 19, 541136, tzinfo=utc), null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='discreption',
            field=models.CharField(blank=True, max_length=130, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 21, 19, 40, 19, 540137, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
