# Generated by Django 3.2.2 on 2021-06-25 05:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20210602_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='corona_help',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 25, 5, 54, 6, 301159, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='catagoery',
            field=models.CharField(blank=True, choices=[('career_tips', 'CAREER_TIPS'), ('life_style', 'LIFE_STYLE'), ('education', 'EDUCATION'), ('psychology', 'PSYCHOLOGY'), ('language', 'LANGUAGE'), ('behaviour', 'BEHAVIOUR')], default='wednesday_weekly', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 25, 5, 54, 6, 301159, tzinfo=utc), null=True),
        ),
    ]
