# Generated by Django 3.2.2 on 2021-06-26 14:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20210625_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corona_help',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 26, 14, 33, 13, 631449, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='catagoery',
            field=models.CharField(blank=True, choices=[('career_tips', 'CAREER_TIPS'), ('life_style', 'LIFE_STYLE'), ('education', 'EDUCATION'), ('psychology', 'PSYCHOLOGY'), ('language', 'LANGUAGE'), ('behaviour', 'BEHAVIOUR'), ('featured', 'FEATURED')], default='wednesday_weekly', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 26, 14, 33, 13, 631449, tzinfo=utc), null=True),
        ),
    ]
