# Generated by Django 3.2.2 on 2021-06-26 14:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20210626_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sub_catagoery',
            field=models.CharField(choices=[('featured', 'FEATURED'), ('not_featured', 'NOT_FEATURED')], default='not_featured', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='corona_help',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 26, 14, 37, 19, 290949, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='catagoery',
            field=models.CharField(blank=True, choices=[('career_tips', 'CAREER_TIPS'), ('life_style', 'LIFE_STYLE'), ('education', 'EDUCATION'), ('psychology', 'PSYCHOLOGY'), ('language', 'LANGUAGE'), ('behaviour', 'BEHAVIOUR')], default='wednesday_weekly', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 26, 14, 37, 19, 290949, tzinfo=utc), null=True),
        ),
    ]
