# Generated by Django 3.2.2 on 2021-07-31 14:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20210703_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corona_help',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 31, 14, 54, 5, 936462, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 31, 14, 54, 5, 935463, tzinfo=utc), null=True),
        ),
    ]
